security:
     classes : "\GL\Core\SecurityService"
     roles : [ ADMIN , USER , TRUSTED_USER ]
     table : users
cookie:
     token : typeyoursecuritytokenhere
     name : REMEMBERME
     duration : 3600