security:
     classes : GL\Core\Security\AuthenticationService
     roles_table : roles
     users_table : users
     usersroles_table : usersroles
cookie:
     token : typeyoursecuritytokenhere
     name : REMEMBERME
     duration : 3600